#!/bin/bash

set -e

CATALINA_HOME=/usr/share/tomcat8-codedeploy
TOMCAT_VERSION=8.5.31

# Tar file name
TOMCAT7_CORE_TAR_FILENAME="apache-tomcat-8.5.31.tar.gz"
# Download URL for Tomcat8 core
TOMCAT7_CORE_DOWNLOAD_URL="http://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.31/bin/apache-tomcat-8.5.31.tar.gz"
# The top-level directory after unpacking the tar file
TOMCAT7_CORE_UNPACKED_DIRNAME="apache-tomcat-$TOMCAT_VERSION"


Check whether there exists a valid instance
of Tomcat7 installed at the specified directory
[[ -d $CATALINA_HOME ]] && { sudo service tomcat8 status; } && {
    echo "Tomcat8 is already installed at $CATALINA_HOME. Skip reinstalling it."
    exit 0
}

# Clear install directory
if [ -d $CATALINA_HOME ]; then
    rm -rf $CATALINA_HOME
fi
mkdir -p $CATALINA_HOME

# Download the latest Tomcat7 version
cd /tmp
{ which wget; } || { sudo apt-get install wget; }
wget $TOMCAT7_CORE_DOWNLOAD_URL
if [[ -d /tmp/$TOMCAT7_CORE_UNPACKED_DIRNAME ]]; then
    rm -rf /tmp/$TOMCAT7_CORE_UNPACKED_DIRNAME
fi
tar xzf $TOMCAT7_CORE_TAR_FILENAME

# Copy over to the CATALINA_HOME
cp -r /tmp/$TOMCAT7_CORE_UNPACKED_DIRNAME/* $CATALINA_HOME

# Install Java if not yet installed
{ which java; } || { sudo add-apt-repository -y ppa:webupd8team/java; }
{ sudo apt-get update; }
{ echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections; }
{ echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections; }
{ sudo apt-get -y install oracle-java8-installer; }

# Create the service init.d script
cat > /etc/init.d/tomcat8 <<'EOF'
#!/bin/bash
# description: Tomcat8 Start Stop Restart
# processname: tomcat8
PATH=$JAVA_HOME/bin:$PATH
export PATH
CATALINA_HOME='/usr/share/tomcat8-codedeploy'

case $1 in
start)
sh $CATALINA_HOME/bin/startup.sh
;;
stop)
sh $CATALINA_HOME/bin/shutdown.sh
;;
restart)
sh $CATALINA_HOME/bin/shutdown.sh
sh $CATALINA_HOME/bin/startup.sh
;;
esac
exit 0
EOF

# Change permission mode for the service script
chmod 755 /etc/init.d/tomcat8